# To build the entire stack run 'make run'
# To build just the errbot chatbot run 'make errbot'

version: '3.9'

services:
  status_page:
    container_name: status_page
    restart: always
    volumes:
      - ./src/status_page/data:/app/data
    ports:
      - 3001:3001
    build:
      context: ./src/status_page
      dockerfile: ./Dockerfile

  nginx_proxy:
    container_name: nginx_proxy
    build:
      context: ./src/nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_NAME=borscht.birki.io
      - BACKEND_ADDR=status_page
      - BACKEND_PORT=3001
    depends_on:
      - status_page
