FROM nginx:mainline-alpine

# set workdir
WORKDIR /app

# Add bash for boot cmd
RUN apk add bash

# Add nginx.conf to container
COPY --chown=nginx:nginx config/nginx.conf /etc/nginx/nginx.conf
# Add the startup file to the container
COPY --chown=nginx:nginx start.sh .

# permissions and nginx user for tightened security
RUN chown -R nginx:nginx /app && chmod -R 755 /app && \
        chown -R nginx:nginx /var/cache/nginx && \
        chown -R nginx:nginx /var/log/nginx && \
        chmod -R 755 /var/log/nginx; \
        chown -R nginx:nginx /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && chown -R nginx:nginx /var/run/nginx.pid

# # Uncomment to keep the nginx logs inside the container - Leave commented for logging to stdout and stderr
# RUN mkdir -p /var/log/nginx
# RUN unlink /var/log/nginx/access.log \
#     && unlink /var/log/nginx/error.log \
#     && touch /var/log/nginx/access.log \
#     && touch /var/log/nginx/error.log \
#     && chown nginx /var/log/nginx/*log \
#     && chmod 644 /var/log/nginx/*log

ADD config/default.conf /tmp/default.conf

USER nginx

EXPOSE 8080

HEALTHCHECK --start-period=5s --timeout=15s --interval=30s \
        CMD curl --fail http://localhost:8080/health-check || exit 1   

CMD ["/app/start.sh"]
